import { CompressionLevel } from '@/hooks/useUserPreferences';

export interface CompressionOptions {
  quality: number;               // Normalized scale between 0.1 and 1.0
  targetFormat?: string;         // 'image/jpeg' | 'image/png' | 'image/webp' | 'image/avif' | 'image/gif'
  stripMetadata?: boolean;       // Set to true for complete privacy cleanup
  onProgress?: (progress: number) => void;
}

export function mapPresetToQuality(level: CompressionLevel): number {
  switch (level) {
    case 'maximum': return 0.4;
    case 'balanced': return 0.7;
    case 'high': return 0.95;
    default: return 0.7;
  }
}

export class ImageService {
  /**
   * Main orchestrator for client-side static and animated image compression pipelines.
   */
  public static async compressImage(file: File, options: CompressionOptions): Promise<Blob> {
    const { quality, targetFormat = file.type, stripMetadata = true, onProgress } = options;
    if (onProgress) onProgress(10);

    // Context Detection: Smart route for animated GIF structures
    if (targetFormat === 'image/gif') {
      return this.compressAnimatedGif(file, quality, onProgress);
    }

    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = async (event) => {
        if (onProgress) onProgress(30);
        const img = new Image();
        img.onload = async () => {
          try {
            const blob = await this.processStaticCanvas(img, targetFormat, quality, stripMetadata, onProgress);
            
            // Commercial Rule: Guard against browser-native compression expansion overflows
            if (blob.size >= file.size) {
              if (onProgress) onProgress(100);
              resolve(file);
              return;
            }
            resolve(blob);
          } catch (err) {
            reject(err);
          }
        };
        img.onerror = () => reject(new Error('Failed to parse input source memory footprint.'));
        img.src = event.target?.result as string;
      };
      reader.onerror = () => reject(new Error('Local memory stream reading failed.'));
      reader.readAsDataURL(file);
    });
  }

  /**
   * Processes all standard static images using canvas layer and high-efficiency quantizers.
   */
  private static async processStaticCanvas(
    img: HTMLImageElement,
    format: string,
    quality: number,
    strip: boolean,
    onProgress?: (p: number) => void
  ): Promise<Blob> {
    if (onProgress) onProgress(50);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Native canvas execution frame rendering failed.');

    canvas.width = img.width;
    canvas.height = img.height;

    if (format === 'image/jpeg') {
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    }
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    if (onProgress) onProgress(70);

    if (format === 'image/png') {
      const UPNG = (await import('upng-js')).default;
      const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const colors = quality >= 0.95 ? 0 : Math.floor(256 * quality);
      const buffer = UPNG.encode([imgData.data.buffer], canvas.width, canvas.height, colors);
      if (onProgress) onProgress(100);
      return new Blob([buffer], { type: 'image/png' });
    }

    return new Promise((resolve, reject) => {
      canvas.toBlob(
        async (blob) => {
          if (!blob) return reject(new Error('Empty stream generated by sandbox context.'));
          if (onProgress) onProgress(90);
          const out = strip ? await this.stripMetadataArray(blob) : blob;
          if (onProgress) onProgress(100);
          resolve(out);
        },
        format,
        quality
      );
    });
  }

  /**
   * Core frame-by-frame extraction loop for animated GIFs utilizing strict omggif structures.
   */
  private static async compressAnimatedGif(file: File, quality: number, onProgress?: (p: number) => void): Promise<Blob> {
    try {
      if (onProgress) onProgress(40);
      const arrayBuffer = await file.arrayBuffer();
      const { GifReader, GifWriter } = await import('omggif');
      
      const reader = new GifReader(new Uint8Array(arrayBuffer));
      const width = reader.width;
      const height = reader.height;
      const numFrames = reader.numFrames();

      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Canvas frame compilation layer missing.');

      const outBuffer = new Uint8Array(width * height * numFrames * 4 + 1024);
      const writer = new GifWriter(outBuffer, width, height, { loop: 0 });
      
      const imgData = ctx.createImageData(width, height);

      for (let i = 0; i < numFrames; i++) {
        reader.decodeAndBlitFrameRGBA(i, imgData.data);
        
        const info = reader.frameInfo(i) as unknown as { delay: number; disposal: number; palette: number[] | null };
        const pixelArray = new Uint8Array(imgData.data.buffer);
        
        writer.addFrame(0, 0, width, height, pixelArray as unknown as number[], {
          delay: info.delay,
          disposal: info.disposal,
          palette: info.palette
        });
      }

      if (onProgress) onProgress(100);
      const compressedBlob = new Blob([outBuffer.subarray(0, writer.end())], { type: 'image/gif' });
      return compressedBlob.size >= file.size ? file : compressedBlob;
    } catch (e) {
      console.warn('GIF animation pipeline exception triggered:', e);
      return file;
    }
  }

  /**
   * Binary EXIF segment dropper for complete privacy compliance across structural markers.
   */
  private static async stripMetadataArray(inputBlob: Blob): Promise<Blob> {
    try {
      const arrayBuffer = await inputBlob.arrayBuffer();
      const view = new DataView(arrayBuffer);
      if (view.getUint16(0, false) !== 0xffd8) return inputBlob;

      let offset = 2;
      const cleanSegments: ArrayBuffer[] = [arrayBuffer.slice(0, 2)];

      while (offset < arrayBuffer.byteLength) {
        const marker = view.getUint16(offset, false);
        if (marker === 0xffda || marker === 0xffd9) {
          cleanSegments.push(arrayBuffer.slice(offset));
          break;
        }
        const segLen = view.getUint16(offset + 2, false);
        const next = offset + 2 + segLen;
        if (marker !== 0xffe1 && marker !== 0xffe2) {
          cleanSegments.push(arrayBuffer.slice(offset, next));
        }
        offset = next;
      }
      return new Blob(cleanSegments, { type: inputBlob.type });
    } catch {
      return inputBlob;
    }
  }
}
